command: ["uvicorn", "agent_server.start_server:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_REGISTRY_URI
    value: "databricks-uc"
  - name: MLFLOW_EXPERIMENT_ID
    value: "404195609266515"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "91dbe14a27ddabad"
  - name: COMPANY_NAME
    value: "Smartsales Memory"
  - name: LAKEBASE_AUTOSCALING_PROJECT
    value: "my-lakebase"
  - name: LAKEBASE_AUTOSCALING_BRANCH
    value: "production"
  - name: UC_CATALOG
    value: "serverless_stable_tcrn2v_catalog"
  - name: UC_SCHEMA
    value: "multiagent_sales_copilot_tbl"
